"""empty message

Revision ID: da8e65cdd9fd
Revises: 87cfa97386db
Create Date: 2020-10-23 06:32:52.260820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8e65cdd9fd'
down_revision = '87cfa97386db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dummy', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
